ncse/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from kdl_ldap.signal_handlers import \
    register_signal_handlers as kdl_ldap_register_signal_hadlers

from periodicals.views import XmodRedirectView

kdl_ldap_register_signal_hadlers()

admin.autodiscover()

urlpatterns = []

try:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
except ImportError:
    pass

urlpatterns += [
    path('admin/', admin.site.urls),
    path('digger/', include('activecollab_digger.urls')),
    path('periodicals/', include('periodicals.urls')),

    path('wagtail/', include('wagtail.admin.urls')),
    path('documents/', include('wagtail.documents.urls')),
    path('cms/', include('wagtail.core.urls')),

    path('Default.htm', XmodRedirectView.as_view(), name='xmod_redir'),

]

# -----------------------------------------------------------------------------
# Static file DEBUGGING
# -----------------------------------------------------------------------------
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    import os.path

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL + 'images/',
        document_root=os.path.join(settings.MEDIA_ROOT, 'images'))

periodicals/urls.py
from django.urls import path

from .views import (ArticleDetailView, ArticlePrintView, IssueDetailView,
                    PageDetailView, PagePrintView, PeriodicalsSearchView,
                    PublicationDetailView, AjaxGalleryFirstEditionsByYear,
                    PublicationListView, AjaxPublicationChartData)

urlpatterns = [
    path('search/', PeriodicalsSearchView.as_view(), name='search'),
    path(('<slug:publication_slug>/'
          'issues/<slug:issue_slug>/'
          'page/<int:number>/'
          'articles/<slug:article_slug>/'),
         ArticleDetailView.as_view(), name='article-detail'),
    path(('<slug:publication_slug>/'
          'issues/<slug:issue_slug>/'
          'page/<int:number>/'
          'articles/<slug:article_slug>/print/'),
         ArticlePrintView.as_view(), name='article-print'),
    path(('<slug:publication_slug>/'
          'issues/<slug:issue_slug>/'
          'page/<int:number>/'),
         PageDetailView.as_view(), name='page-detail'),
    path(('<slug:publication_slug>/'
          'issues/<slug:issue_slug>/'
          'page/<int:number>/print/'),
         PagePrintView.as_view(), name='page-print'),
    path('<slug:publication_slug>/issues/<slug:slug>/',
         IssueDetailView.as_view(), name='issue-detail'),
    path('<slug:slug>/',
         PublicationDetailView.as_view(), name='publication-detail'),
    path('ajax/first_editions/<slug:slug>/<int:year>/',
         AjaxGalleryFirstEditionsByYear.as_view(),
         name='ajax-gallery-first-ed'),
    path('ajax/chart_data/<slug:slug>/',
         AjaxPublicationChartData.as_view(),
         name='ajax-publication-chart-data'),
    path('', PublicationListView.as_view(), name='publication-list'),
]

periodicals/models.py
from django.contrib.humanize.templatetags.humanize import ordinal
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models import Sum, Q
from django.urls import reverse
from django.utils.text import slugify


class Publication(models.Model):
    abbreviation = models.CharField(max_length=5)
    slug = models.SlugField(max_length=5)
    title = models.CharField(max_length=256, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    ordering = models.PositiveIntegerField(blank=True, null=True)
    title_image = models.ImageField(null=True, blank=True)
    year_from = models.PositiveIntegerField(blank=True, null=True)
    year_to = models.PositiveIntegerField(blank=True, null=True)
    page_count = models.PositiveIntegerField(default=0)
    issue_count = models.PositiveIntegerField(default=0)
    article_count = models.PositiveIntegerField(default=0)
    headnotes_url = models.CharField(max_length=128, blank=True,
                                     null=True)
    weekly = models.BooleanField(default=True)

    class Meta:
        ordering = ['ordering']
        unique_together = ('abbreviation', 'slug', 'title')

    def __str__(self):
        return '{}'.format(self.title if self.title else self.abbreviation)

    @property
    def date_format(self):
        if self.weekly:
            return "jS F Y"
        else:
            return "F Y"

    @property
    def url(self):
        return reverse(
            'publication-detail', kwargs={
                'slug': self.slug
            })

    def get_year_span(self):
        return [self.year_from, self.year_to]

    def get_year_range(self):
        return range(self.year_from, self.year_to + 1)

    def get_number_of_years(self):
        if self.year_to and self.year_from:
            return (self.year_to - self.year_from) + 1
        else:
            return 0

    @property
    def get_issues(self):
        return Issue.objects.filter(publication=self)

    @property
    def get_first_issues(self):
        return Issue.objects.filter(publication=self).filter(edition=1)

    @property
    def primary_issue_count(self):
        return self.get_issues.filter(
            component=None
        ).filter(
            Q(edition='1') | Q(edition='Town') | Q(edition='Country')
        ).count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.abbreviation)
        if self.issues.all().count():

            # Save issue count
            self.issue_count = self.issues.all().count()
            # Save ordering
            self.ordering = self.issues.first().issue_date.year

            # Save year span
            self.year_from = self.issues.first().issue_date.year
            self.year_to = self.issues.last().issue_date.year

            # Save page counts
            aggregation = self.issues.aggregate(
                total_pages=Sum('number_of_pages'))
            if aggregation:
                self.page_count = aggregation['total_pages']

            # Save article counts
            aggregation_ar = self.issues.aggregate(
                total_articles=Sum('article_count'))
            if aggregation_ar:
                self.article_count = aggregation_ar['total_articles']

        super(Publication, self).save(*args, **kwargs)


class IssueComponent(models.Model):
    title = models.CharField(
        max_length=256, blank=False, null=False, unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Issue(models.Model):
    publication = models.ForeignKey(Publication, related_name='issues',
                                    on_delete=models.CASCADE)
    uid = models.CharField(max_length=32, unique=True)
    slug = models.CharField(max_length=32, unique=True)
    issue_date = models.DateField()
    component = models.ForeignKey(IssueComponent, blank=True, null=True,
                                  on_delete=models.CASCADE)
    edition = models.CharField(max_length=128, blank=True, null=True,)
    number_of_pages = models.PositiveIntegerField(blank=True, null=True)
    pdf = models.FileField(upload_to='periodicals/', null=True)
    article_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['issue_date', 'edition']

    def __str__(self):
        issue = '{}: {}'.format(self.publication, self.issue_date.strftime(
            self.publication.date_format))

        if self.edition != 1:
            issue = '{}, {} edition'.format(issue, ordinal(self.edition))

        if self.component:
            issue = '{}, {}'.format(issue, self.component)

        return issue

    @property
    def edition_or_component(self):
        issue = ''

        if self.edition != 1:
            issue = '{} edition'.format(ordinal(self.edition))

        if self.component:
            issue = '{}, {}'.format(issue, self.component)

        return issue

    @property
    def name(self):
        issue = ''

        if self.edition != 1:
            issue = '{} edition'.format(ordinal(self.edition))

        if self.component:
            issue = '{}, {}'.format(issue, self.component)

        if issue == '':
            return "Unknown Issue"
        else:
            return issue

    @property
    def departments(self):
        return self.get_base_query().filter(
            is_department=True)

    @property
    def articles(self):
        article = ArticleType.objects.get_or_create(title='Article')[0]
        return self.get_base_query().filter(article_type=article)

    @property
    def ads(self):
        ad = ArticleType.objects.get_or_create(title='Ad')[0]
        return self.get_base_query().filter(article_type=ad)

    @property
    def items(self):
        return self.get_base_query()

    @property
    def pictures(self):
        picture = ArticleType.objects.get_or_create(title='Picture')[0]
        return self.get_base_query().filter(article_type=picture)

    @property
    def url(self):
        return reverse(
            'issue-detail', kwargs={
                'publication_slug': self.publication.slug,
                'slug': self.slug
            })

    def get_components(self):
        return self.publication.issues.filter(
            issue_date=self.issue_date, edition=self.edition).exclude(
                uid=self.uid)

    def get_editions(self):
        return self.publication.issues.filter(
            issue_date=self.issue_date).exclude(
            edition=self.edition).order_by('edition')

    def get_edition_count(self):
        return self.publication.issues.filter(
            issue_date=self.issue_date).values('edition').distinct().count()

    def get_base_query(self):
        return self.articles_in_issue.select_related(
            'page').defer(
            'content', 'content_html', 'bounding_box', 'page__words').filter(
            continuation_from=None)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.uid)
        self.article_count = self.articles_in_issue.filter(
            continuation_from=None).count()

        # Resave publication!
        self.publication.save()
        super(Issue, self).save(*args, **kwargs)


class Page(models.Model):
    height = models.PositiveIntegerField(null=True)
    issue = models.ForeignKey(Issue, related_name='pages',
                              on_delete=models.CASCADE)
    number = models.PositiveIntegerField()
    label = models.CharField(max_length=64, blank=True, null=True)
    image = models.ImageField(upload_to='periodicals/')
    width = models.PositiveIntegerField(null=True)
    words = JSONField(default='{}', null="true")
    article_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return '{}: {}'.format(self.issue, self.number)

    @property
    def departments(self):
        return self.get_base_query().filter(
            is_department=True)

    @property
    def articles(self):
        article = ArticleType.objects.get_or_create(title='Article')[0]
        return self.get_base_query().filter(article_type=article)

    @property
    def ads(self):
        ad = ArticleType.objects.get_or_create(title='Ad')[0]
        return self.get_base_query().filter(article_type=ad)

    @property
    def items(self):
        return self.get_base_query()

    @property
    def pictures(self):
        picture = ArticleType.objects.get_or_create(title='Picture')[0]
        return self.get_base_query().filter(article_type=picture)

    @property
    def number_of_articles(self):
        return self.article_count

    @property
    def url(self):
        return reverse(
            'page-detail', kwargs={
                'publication_slug': self.issue.publication.slug,
                'issue_slug': self.issue.slug, 'number': self.number
            })

    @property
    def print_url(self):
        return reverse(
            'page-print', kwargs={
                'publication_slug': self.issue.publication.slug,
                'issue_slug': self.issue.slug, 'number': self.number
            })

    def get_label(self):
        if self.label:
            return self.label

        return self.number

    def previous_page(self):
        if self.number > 1:
            return self.issue.pages.all()[self.number - 2]
        else:
            return None

    def next_page(self):
        if self.issue.number_of_pages > self.number:
            return self.issue.pages.all()[self.number]
        else:
            return None

    def get_base_query(self):
        return Article.objects.filter(page=self).select_related(
            'page').defer(
            'content', 'content_html', 'bounding_box', 'page__words').filter(
            continuation_from=None)

    def save(self, *args, **kwargs):
        self.article_count = self.articles.count()
        self.issue.save()
        super(Page, self).save(*args, **kwargs)

periodicals/forms.py
from django import forms
from django.forms.widgets import RadioSelect
from haystack.forms import FacetedSearchForm


class PeriodicalsSearchForm(FacetedSearchForm):

    MODE_DEFAULT = ('or', 'Any word')
    MODE_AND = ('and', 'All words')
    MODE_PHRASE = ('phrase', 'Phrase')
    MODE_CHOICES = (MODE_DEFAULT, MODE_AND, MODE_PHRASE)
    mode = forms.ChoiceField(
        choices=MODE_CHOICES, initial=MODE_DEFAULT[0], widget=RadioSelect)

    start_year = forms.IntegerField(required=False, initial=1806,
                                    widget=forms.NumberInput(
                                        attrs={'aria-label': 'Start Year'}))
    end_year = forms.IntegerField(required=False, initial=1890,
                                  widget=forms.NumberInput(
                                      attrs={'aria-label': 'End Year'}))
    q = forms.CharField(required=False, initial=1806,
                        widget=forms.TextInput(
                            attrs={'aria-label': 'Keywords'}))

    ORDER_BY_DEFAULT = ('issue_date', 'Date')
    ORDER_BY_TITLE = ('title', 'Title')
    ORDER_BY_RELEVANCE = ('score', 'Relevance')
    ORDER_BY_CHOICES = (ORDER_BY_DEFAULT, ORDER_BY_TITLE, ORDER_BY_RELEVANCE)
    order_by = forms.ChoiceField(
        choices=ORDER_BY_CHOICES, initial=ORDER_BY_DEFAULT[0],
        widget=RadioSelect)

    def no_query_found(self):
        return self.searchqueryset.all()

    def search(self):
        sqs = super(PeriodicalsSearchForm, self).search()

        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['mode'] and self.cleaned_data['q']:
            mode = self.cleaned_data['mode']
            query = self.cleaned_data['q']

            if mode == self.MODE_DEFAULT[0]:
                words = query.split()
                for word in words:
                    sqs = sqs.filter_or(content=word)
            elif mode == self.MODE_AND[0]:
                words = query.split()
                for word in words:
                    sqs = sqs.filter(content=word)
            elif mode == self.MODE_PHRASE[0]:
                sqs = sqs.filter(content__exact=self.cleaned_data['q'])

        if self.cleaned_data['start_year']:
            sqs = sqs.filter(issue_year__gte=self.cleaned_data['start_year'])

        if self.cleaned_data['end_year']:
            sqs = sqs.filter(issue_year__lte=self.cleaned_data['end_year'])

        return sqs

periodicals/templates/periodicals/article_print.html
<html>
<head>
    <title>{{article.issue}} - {{ article|title }}</title>

    <style type="text/css">
    @media print {
        html,
        body {
            margin: 0;
            padding: 0;
            height: 100%;
        }

        .page {
            height: 90%;
        }

        .page img {
            display: block;
            max-height: 100%;
            margin: 0 auto;
        }
    }
    </style>
</head>

<body>
    {% for p in pages %}
    <div class="page">
        <img src="{{ p.image.url }}" alt="{{article.issue}} - {{ article|title }}">
    </div>
    {% endfor %}
    <script>
    setTimeout(function () { window.close(); }, 2000);
    window.print();
    </script>
</body>
</html>

periodicals/templates/periodicals/base.html
{% extends 'base.html' %}
{% block breadcrumbs %}
    {% include 'periodicals/includes/breadcrumbs.html' %}
{% endblock %}

periodicals/templates/periodicals/issue_detail.html
{% extends 'periodicals/base.html' %}
{% load humanize periodicals_tags %}

{% block title %}
{{ issue.publication}}, {{ issue.issue_date|date:issue.publication.date_format }}, Edition {{issue.edition}} of {{ issue.get_edition_count }}{% if issue.component %}, {{issue.component}}{% endif %}


{% if issue.pdf %}
 <a class="float-right" href="{{ issue.pdf.url}}" target="" class="noselect" download><span class="buttonicon"></span></a></span>
{% endif %}
{% endblock %}



{% block meta_title %}
{{ issue }}
{% endblock %}

{% block main %}


{% with ads=issue.ads departments=issue.departments articles=issue.articles pictures=issue.pictures editions=issue.get_editions components=issue.get_components %}



<div class="row" id="main">
    <div class="small-12 medium-3 columns" data-sticky-container>
        <div class="sticky" data-sticky data-anchor="main">
            <div class="menu vertical ">
                <ul class="vertical tabs menu" data-tabs id="issue-nav">
                    <h2>In this issue</h2>
                    {% if departments %}
                    <li class="tabs-title is-active">
                        <a href="#departments">Departments <span>({{departments.count}})</span></a>
                    </li>
                    {% endif %}
                    {% if ads %}
                    <li class="tabs-title{% if not departments %} is-active{% endif %}">
                        <a href="#ads">Adverts <span>({{ ads.count }})</i></span></a>
                    </li>
                    {% endif %}
                    {% if pictures %}
                    <li class="tabs-title{% if not departments and not ads %} is-active{% endif %}">
                        <a href="#images">Pictures <span>({{pictures.count}})</i></span></a>
                    </li>
                    {% endif %}
                    {% if articles %}
                    <li class="tabs-title{% if not departments and not ads and not pictures %} is-active{% endif %}">
                        <a href="#text">Text <span>({{ articles.count}})</i></span></a>
                    </li>
                    {% endif %}
                    {% if editions %}
                     <h3 class="tabs-title">
                        <a href="#editions">Other Editions <span>({{ editions.count}})</i></span></a>
                    </h3>
                    {% endif %}
                    {% if components %}
                    <h3 class="tabs-title">
                        <a href="#components">Other Components <span>({{ components.count}})</i></span></a>
                    </h3>
                    {% endif %}
                     <h3 class="tabs-title">
                        <a href="#pages">Pages <span>({{ issue.number_of_pages }})</span></a>
                    </h3>
                </ul>
            </div>
        </div>
    </div>


    <div class="medium-9 columns tabs-content" data-tabs-content="issue-nav">
        {% if departments %}
        <div class="row margin-bottom tabs-panel is-active" id="departments">
            <div class="column">


            <h2 class="underline">Departments</h2>
            {% include "periodicals/includes/ocr_warning.html" %}
            </div>

            {% regroup departments by page as page_list %}
            {% for page in page_list %}
                {% for department in page.list %}
                    <div class="medium-2 columns">
                        {% if forloop.first %}
                        Page {{ page.grouper.get_label }}
                        {% endif %}
                    </div>
                    <div class="medium-10 columns margin-bottom">
                        <a href="{% url 'article-detail' publication_slug=department.page.issue.publication.slug issue_slug=department.page.issue.slug number=department.page.number article_slug=department.slug%}">
                            <img class="border" src="{% thumbnail department.title_image.url %}" alt="Snippet of {{ issue.publication}}">
                            <p>
                            {% if department %}{{ department}}{% else %}Untitled{% endif %}
                            </p>
                        </a>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
        {% endif %}


        {% if ads %}

        <div class="row margin-bottom tabs-panel{% if not departments %} is-active{% endif %}" id="ads">
        <div class="column">
        <h2 class="underline">Adverts</h2>
        {% include "periodicals/includes/ocr_warning.html" %}
        </div>
        {% include "periodicals/includes/issue_toc.html" with items=ads %}
        </div>
        {% endif %}

        {% if pictures %}
        <div class="row margin-bottom tabs-panel{% if not departments and not ads %} is-active{% endif %}" id="images">
        <div class="column">
        <h2 class="underline">Images</h2>
        {% include "periodicals/includes/pic_warning.html" %}
        </div>
        {% include "periodicals/includes/issue_toc.html" with items=pictures %}
        </div>
        {% endif %}

        {% if articles %}
        <div class="row margin-bottom tabs-panel{% if not departments and not ads and not pictures %} is-active{% endif %}" id="text">
        <div class="column">
        <h2 class="underline">Text</h2>
        {% include "periodicals/includes/ocr_warning.html" %}
        </div>
        {% include "periodicals/includes/issue_toc.html" with items=articles %}
        </div>
        {% endif %}


        {% if components %}
        <div class="row margin-bottom tabs-panel" id="components">
        <div class="column">
        <h2 class="underline margin-bottom">Other Components</h2>
        {% include "periodicals/includes/issue_gallery.html" with issues=components %}
        </div>
        </div>
        {% endif %}

        {% if editions %}
        <div class="row margin-bottom tabs-panel" id="editions">
        <div class="column">
        <h2 class="underline margin-bottom">Other Editions</h2>
        {% include "periodicals/includes/issue_gallery.html" with issues=editions %}
        </div>
        </div>
        {% endif %}

        <div class="row margin-bottom tabs-panel" id="pages">
        <div class="column">
        <h2 class="underline margin-bottom">Pages</h2>
        {% include "periodicals/includes/page_gallery.html" with pages=issue.pages.all %}
        </div>
        </div>

    </div>
</div>

{% endwith %}

{% endblock %}

periodicals/templates/periodicals/page_print.html
<html>
<head>
    <title>{{ page }}</title>

    <style type="text/css">
    @media print {
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
        }

        .page
        {
            height: 90%;
        }

        .page img
        {
            display: block;
            max-height: 100%;
            margin: 0 auto;
        }
    }
    </style>
</head>
<body>
    <div class="page">
        <img src="{{ page.image.url }}" alt="{{ page }}">
    </div>
    <script>
    setTimeout(function () { window.close(); }, 2000);
    window.print();
    </script>
</body>
</html>

periodicals/templates/periodicals/publication_detail.html
{% extends 'periodicals/base.html' %}
{% load periodicals_tags %}
{% load staticfiles %}


{% block meta_title %}
{{ publication }}
{% endblock %}

{% block title %}
{{ publication }}
{% endblock %}

{% block main %}

{% if publication.description %}
<section>
    <div class="row">
        <div class="small-12 columns">
            <h3>Description</h3>
            <div class="description-trunk">
                {{ publication.description | truncatewords_html:40 }}
                <a class="read-more" data-target="#description-full">Read more</a>
            </div>
            <div class="description-full" id="description-full">
                {{ publication.description }}
            </div>
        </div>
    </div>
</section>
{% endif %}



<section>
    <div class="row">
        <div class="small-12 columns">
            {% include "periodicals/includes/vis.html" with show_info=1 class="publication" %}
        </div>
    </div>
</section>





<!-- New template but no tags -->
<div class="row" id="main">
    <div class="medium-3 columns">
        <ul class="vertical menu" data-accordion  data-accordion-menu data-multi-open="false">
        {% if publication.headnotes_url %}
        <li><a class="menu Link" href="{{ publication.headnotes_url }}">About this publication</a></li>
        {% endif %}

        <h2>Years</h2>
            {% for year in publication.get_year_range %}
                {% with issues=publication|get_issues_by_year:year %}
                {% if issues %}
                <li >
                    <a href="{% url 'ajax-gallery-first-ed' slug=publication.slug year=year %}" class="ajax-trigger-year-switcher {% if forloop.first %} ajax-active {% endif %}" data-year="{{ year }}" >{{year}} </a>
                    <ul class="menu vertical">
                        {% regroup issues by issue_date as dates %}
                        {% for date in dates %}
                        <li>
                            <a href="#">{{ date.grouper|date:publication.date_format }} <span>({{date.list|length}})</span></a>
                            <ul class="menu vertical">
                                {% for issue in date.list %}
                                <li {% if issue.edition != '1' %}class="lighten" {% endif %}><a href="{{issue.url}}">{{ issue.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endif %}
                {% endwith %}
            {% endfor %}
        </ul>
    </div>
    <!-- Cards -->
    <div class="medium-9 columns" id="ajax-target-gallery">
    {% include "periodicals/includes/issue_gallery.html" with issues=publication|get_first_issues_by_year:publication.year_from %}
    </div>
</div>



{% endblock %}

periodicals/templates/periodicals/publication_list.html
{% extends "periodicals/base.html" %}
{% load periodicals_tags %}

{% block title %}Facsimiles{% endblock %}

{% block meta_title %}Publications | Facsimiles{% endblock %}

{% block breadcrumbs %}
<li><a href="/">Home</a></li>
<li>Facsimiles</li>
{% endblock %}

{% block main %}

<section>
    <div class="row">
        <div class="large-12 columns">
            {% get_publications %}
        </div>

        
    </div>

</section>
{% endblock %}